# Generated by Django 5.1.5 on 2025-02-08 10:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_team_github"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="backend_technologies",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="database_technology",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="frontend_technologies",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="other_technologies",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="echnologies",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
